# =============================================================================
# CLIF K8s — ConfigMap Generator Script
# =============================================================================
# Generates ConfigMaps from large source files (schema.sql, vector.yaml,
# grafana-dashboard.json) that are too large to inline comfortably.
#
# Usage: .\k8s\generate-configmaps.ps1
# =============================================================================

$ErrorActionPreference = "Stop"
$ROOT = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
if (-not $ROOT) { $ROOT = (Get-Location).Path }

Write-Host "=== CLIF K8s ConfigMap Generator ===" -ForegroundColor Cyan
Write-Host "Root directory: $ROOT"

# ── Generated output directory ────────────────────────────────────────────────
$OUT = Join-Path $ROOT "k8s" "base" "configmaps" "generated"
if (-not (Test-Path $OUT)) {
    New-Item -ItemType Directory -Path $OUT -Force | Out-Null
}

# ── Helper: Create ConfigMap YAML from file ──────────────────────────────────
function New-ConfigMapFromFile {
    param(
        [string]$Name,
        [string]$SourceFile,
        [string]$DataKey,
        [string]$OutputFile
    )
    
    if (-not (Test-Path $SourceFile)) {
        Write-Warning "  Source not found: $SourceFile — skipping $Name"
        return
    }

    $fileSize = (Get-Item $SourceFile).Length
    Write-Host "  Generating $Name ($DataKey, $([math]::Round($fileSize/1024,1))KB)..."

    $content = Get-Content -Path $SourceFile -Raw
    # Indent every line by 4 spaces for YAML literal block
    $indented = ($content -split "`n" | ForEach-Object { "    $_" }) -join "`n"

    $yaml = @"
# Auto-generated by generate-configmaps.ps1 — DO NOT EDIT
# Source: $($SourceFile -replace [regex]::Escape($ROOT), '.')
apiVersion: v1
kind: ConfigMap
metadata:
  name: $Name
  namespace: clif
  labels:
    app.kubernetes.io/part-of: clif-siem
    generated: "true"
data:
  $DataKey`: |
$indented
"@

    $yaml | Set-Content -Path $OutputFile -Encoding UTF8 -NoNewline
    Write-Host "    -> $OutputFile" -ForegroundColor Green
}

# ── Generate ConfigMaps ──────────────────────────────────────────────────────
Write-Host "`nGenerating ConfigMaps from source files..." -ForegroundColor Yellow

New-ConfigMapFromFile `
    -Name "clickhouse-schema" `
    -SourceFile (Join-Path $ROOT "clickhouse" "schema.sql") `
    -DataKey "schema.sql" `
    -OutputFile (Join-Path $OUT "clickhouse-schema.yaml")

New-ConfigMapFromFile `
    -Name "vector-config" `
    -SourceFile (Join-Path $ROOT "vector" "vector.yaml") `
    -DataKey "vector.yaml" `
    -OutputFile (Join-Path $OUT "vector-config.yaml")

New-ConfigMapFromFile `
    -Name "grafana-dashboard" `
    -SourceFile (Join-Path $ROOT "monitoring" "grafana-dashboard.json") `
    -DataKey "grafana-dashboard.json" `
    -OutputFile (Join-Path $OUT "grafana-dashboard.yaml")

# ── Verify ───────────────────────────────────────────────────────────────────
Write-Host "`nGenerated ConfigMaps:" -ForegroundColor Cyan
Get-ChildItem -Path $OUT -Filter "*.yaml" | ForEach-Object {
    $size = [math]::Round($_.Length / 1024, 1)
    Write-Host "  $($_.Name) ($size KB)" -ForegroundColor White
}

Write-Host "`nDone! Run 'kubectl apply -k k8s/base/' to deploy." -ForegroundColor Green
