#!/usr/bin/env bash
# =============================================================================
# CLIF Cluster — MacBook Setup Script
# =============================================================================
# Run on the MacBook after cloning the CLIF repo.
# Detects LAN IP, configures cluster/.env, and validates Docker + connectivity.
#
# Usage:
#   chmod +x cluster/setup-mac.sh
#   ./cluster/setup-mac.sh                      # interactive
#   ./cluster/setup-mac.sh --data-ip 192.168.1.100  # non-interactive
# =============================================================================

set -euo pipefail
cd "$(dirname "$0")/.."

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "\n${CYAN}${BOLD}========================================"
echo "  CLIF Cluster — MacBook Setup"
echo -e "========================================${NC}\n"

# ── Parse args ──────────────────────────────────────────────────────────────
DATA_IP=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --data-ip) DATA_IP="$2"; shift 2 ;;
    *) echo -e "${RED}Unknown arg: $1${NC}"; exit 1 ;;
  esac
done

# ── 1. Detect local LAN IP ─────────────────────────────────────────────────
get_lan_ip() {
  # macOS: use route + ifconfig to find the active LAN interface IP
  local iface
  iface=$(route -n get default 2>/dev/null | awk '/interface:/{print $2}')
  if [[ -n "$iface" ]]; then
    ifconfig "$iface" | awk '/inet /{print $2}' | head -1
  fi
}

LOCAL_IP=$(get_lan_ip)
echo -e "This MacBook's LAN IP: ${YELLOW}${LOCAL_IP:-unknown}${NC}"

if [[ -z "$DATA_IP" ]]; then
  echo -e "\n${BOLD}Enter PC1 (Windows) LAN IP address:${NC}"
  echo -e "  (Find it on PC1 with: ipconfig | findstr IPv4)"
  read -rp "  PC1 IP> " DATA_IP
fi

if [[ -z "$DATA_IP" || "$DATA_IP" == "CHANGE_ME" ]]; then
  echo -e "${RED}ERROR: DATA_IP is required. Provide PC1's LAN IP.${NC}"
  exit 1
fi

echo -e "\n${GREEN}PC1 (Data tier): ${DATA_IP}${NC}"
echo -e "${GREEN}Mac (Compute):   ${LOCAL_IP:-this machine}${NC}"

# ── 2. Validate Docker ─────────────────────────────────────────────────────
echo -e "\n${YELLOW}Checking Docker...${NC}"
if ! docker version --format '{{.Server.Version}}' >/dev/null 2>&1; then
  echo -e "${RED}ERROR: Docker is not running. Start Docker Desktop first.${NC}"
  exit 1
fi
DOCKER_VER=$(docker version --format '{{.Server.Version}}')
echo -e "  Docker Engine: ${GREEN}${DOCKER_VER}${NC}"

if ! docker compose version --short >/dev/null 2>&1; then
  echo -e "${RED}ERROR: Docker Compose v2 not found.${NC}"
  exit 1
fi
COMPOSE_VER=$(docker compose version --short)
echo -e "  Compose:       ${GREEN}${COMPOSE_VER}${NC}"

# Check Docker has enough resources for M1
DOCKER_CPUS=$(docker info --format '{{.NCPU}}' 2>/dev/null || echo "?")
DOCKER_MEM=$(docker info --format '{{.MemTotal}}' 2>/dev/null || echo "?")
echo -e "  Docker CPUs:   ${GREEN}${DOCKER_CPUS}${NC}"
echo -e "  Docker Memory: ${GREEN}$(echo "$DOCKER_MEM" | awk '{printf "%.1f GB", $1/1024/1024/1024}')${NC}"

# ── 3. Verify ARM64 architecture ───────────────────────────────────────────
ARCH=$(uname -m)
echo -e "\n${YELLOW}Architecture: ${ARCH}${NC}"
if [[ "$ARCH" == "arm64" ]]; then
  echo -e "  ${GREEN}✔ Apple Silicon (M1) — native ARM64 builds${NC}"
else
  echo -e "  ${YELLOW}⚠ Not ARM64 — images will use emulation (slower)${NC}"
fi

# ── 4. Write cluster/.env ──────────────────────────────────────────────────
mkdir -p cluster
cat > cluster/.env <<EOF
# Auto-generated by setup-mac.sh on $(date '+%Y-%m-%d %H:%M')
# Role: mac (compute tier) | DATA_IP: ${DATA_IP}
DATA_IP=${DATA_IP}
REDPANDA_MEMORY=1500M
REDPANDA_MEM_LIMIT=2G
REDPANDA_SMP=1
EOF

echo -e "\n${GREEN}Wrote cluster/.env  (DATA_IP=${DATA_IP})${NC}"

# ── 5. Test connectivity to PC1 ────────────────────────────────────────────
echo -e "\n${YELLOW}Testing connectivity to PC1 (${DATA_IP})...${NC}"

check_port() {
  local host=$1 port=$2 name=$3
  if nc -z -w 2 "$host" "$port" 2>/dev/null; then
    echo -e "  ${GREEN}✔ ${name} (${port})${NC}"
    return 0
  else
    echo -e "  ${YELLOW}✗ ${name} (${port}) — start PC1 first or check firewall${NC}"
    return 1
  fi
}

PORTS_OK=0
check_port "$DATA_IP" 19092 "Redpanda Kafka"      && ((PORTS_OK++)) || true
check_port "$DATA_IP" 8123  "ClickHouse HTTP"      && ((PORTS_OK++)) || true
check_port "$DATA_IP" 9000  "ClickHouse Native"    && ((PORTS_OK++)) || true
check_port "$DATA_IP" 9002  "MinIO Data"           && ((PORTS_OK++)) || true

if [[ $PORTS_OK -eq 4 ]]; then
  echo -e "\n  ${GREEN}${BOLD}All 4 ports reachable — PC1 is ready!${NC}"
elif [[ $PORTS_OK -gt 0 ]]; then
  echo -e "\n  ${YELLOW}${PORTS_OK}/4 ports reachable — some services may not be started yet${NC}"
else
  echo -e "\n  ${RED}No ports reachable — ensure PC1 is running and firewall allows traffic${NC}"
fi

# ── 6. Show next steps ─────────────────────────────────────────────────────
echo -e "\n${CYAN}${BOLD}========================================"
echo "  Setup Complete — Next Steps"
echo -e "========================================${NC}\n"

cat <<EOF
  1. Ensure PC1 is running and healthy:
     (On PC1) docker compose -f docker-compose.pc1.yml --env-file .env --env-file cluster/.env ps

  2. Start the MacBook compute tier:
     docker compose -f docker-compose.mac.yml --env-file .env --env-file cluster/.env up -d

  3. With LanceDB semantic search:
     docker compose -f docker-compose.mac.yml --env-file .env --env-file cluster/.env --profile full up -d

  4. Check status:
     docker compose -f docker-compose.mac.yml ps

  5. Verify:
     curl http://localhost:8300/health    # Triage Agent
     curl http://localhost:8400/health    # Hunter Agent
     curl http://localhost:8686/health    # Vector
     Grafana:           http://localhost:3002
     Redpanda Console:  http://localhost:8080

  PC1 Windows Firewall — ensure these ports are open:
     19092, 29092, 39092  (Redpanda Kafka)
     8123, 9000           (ClickHouse)
     9002                 (MinIO)
     9363, 9364           (ClickHouse metrics)
     9644, 9645, 9646     (Redpanda admin)

EOF
