# =============================================================================
# CLIF Cluster — Setup Script
# =============================================================================
# Run on BOTH PCs after cloning the CLIF repo.
# Detects LAN IP, configures cluster/.env, and validates Docker.
# =============================================================================

param(
    [ValidateSet("pc1","pc2")]
    [string]$Role,

    [string]$DataIP
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot\..

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  CLIF Cluster Setup" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

# ── 1. Detect / validate LAN IP ────────────────────────────────────────────
function Get-LanIP {
    $addrs = Get-NetIPAddress -AddressFamily IPv4 |
        Where-Object { $_.PrefixOrigin -eq "Dhcp" -or $_.PrefixOrigin -eq "Manual" } |
        Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "172.1*" -and $_.IPAddress -notlike "169.*" } |
        Select-Object -ExpandProperty IPAddress
    if ($addrs -is [array]) { return $addrs[0] } else { return $addrs }
}

if (-not $DataIP) {
    $detected = Get-LanIP
    if (-not $Role) {
        Write-Host "This machine's LAN IP: $detected" -ForegroundColor Yellow
        $Role = Read-Host "Role for this PC? (pc1 = data tier, pc2 = compute tier)"
    }
    if ($Role -eq "pc1") {
        $DataIP = $detected
        Write-Host "Using this machine's IP as DATA_IP: $DataIP" -ForegroundColor Green
    } else {
        $DataIP = Read-Host "Enter PC1's LAN IP address"
    }
}

if (-not $Role) {
    $Role = Read-Host "Role for this PC? (pc1 / pc2)"
}

# ── 2. Validate Docker ────────────────────────────────────────────────────
Write-Host "`nChecking Docker..." -ForegroundColor Yellow
try {
    $ver = docker version --format '{{.Server.Version}}' 2>$null
    Write-Host "  Docker Engine: $ver" -ForegroundColor Green
} catch {
    Write-Host "  ERROR: Docker is not running. Start Docker Desktop first." -ForegroundColor Red
    exit 1
}

try {
    $composeVer = docker compose version --short 2>$null
    Write-Host "  Compose:       $composeVer" -ForegroundColor Green
} catch {
    Write-Host "  ERROR: Docker Compose v2 not found." -ForegroundColor Red
    exit 1
}

# ── 3. Write cluster/.env ─────────────────────────────────────────────────
$envContent = @"
# Auto-generated by setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
# Role: $Role | DATA_IP: $DataIP
DATA_IP=$DataIP
REDPANDA_MEMORY=1500M
REDPANDA_MEM_LIMIT=2G
REDPANDA_SMP=1
"@

$envContent | Set-Content -Path "cluster\.env" -Encoding UTF8
Write-Host "`nWrote cluster\.env  (DATA_IP=$DataIP)" -ForegroundColor Green

# ── 4. Validate connectivity to PC1 (for PC2 only) ────────────────────────
if ($Role -eq "pc2") {
    Write-Host "`nTesting connectivity to PC1 ($DataIP)..." -ForegroundColor Yellow

    $ports = @(
        @{Port=19092; Name="Redpanda01 Kafka"},
        @{Port=8123;  Name="ClickHouse01 HTTP"},
        @{Port=9000;  Name="ClickHouse01 Native"},
        @{Port=9002;  Name="MinIO Data"}
    )

    foreach ($p in $ports) {
        try {
            $tcp = New-Object System.Net.Sockets.TcpClient
            $tcp.ConnectAsync($DataIP, $p.Port).Wait(2000) | Out-Null
            if ($tcp.Connected) {
                Write-Host "  OK  $($p.Name) ($($p.Port))" -ForegroundColor Green
            } else {
                Write-Host "  WAIT $($p.Name) ($($p.Port)) — start PC1 first" -ForegroundColor Yellow
            }
            $tcp.Close()
        } catch {
            Write-Host "  WAIT $($p.Name) ($($p.Port)) — start PC1 first" -ForegroundColor Yellow
        }
    }
}

# ── 5. Show next steps ────────────────────────────────────────────────────
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Setup Complete — Next Steps" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

if ($Role -eq "pc1") {
    Write-Host @"
  1. Start the data tier:
     docker compose -f docker-compose.pc1.yml --env-file .env --env-file cluster\.env up -d

  2. Wait for all services to be healthy:
     docker compose -f docker-compose.pc1.yml ps

  3. Run this same script on PC2 with: .\cluster\setup.ps1 -Role pc2 -DataIP $DataIP

  4. Windows Firewall: ensure these ports are open for PC2:
     19092, 29092, 39092 (Redpanda Kafka)
     8123, 9000          (ClickHouse)
     9002                (MinIO)
     9363, 9364          (ClickHouse metrics — if monitoring)
     9644, 9645, 9646    (Redpanda admin — if monitoring)

"@ -ForegroundColor White
} else {
    Write-Host @"
  1. Ensure PC1 is running and healthy first!

  2. Start the compute tier (includes Prometheus + Grafana):
     docker compose -f docker-compose.pc2.yml --env-file .env --env-file cluster\.env up -d

  3. Start the dashboard:
     cd dashboard
     # Edit .env.local: set CH_HOST=$DataIP
     npm run dev

  4. Verify: open http://localhost:3001 in browser
     Grafana: http://localhost:3002
     Redpanda Console: http://localhost:8080

"@ -ForegroundColor White
}

Write-Host "Health check:  .\cluster\health-check.ps1 -Role $Role -DataIP $DataIP`n" -ForegroundColor Gray
