apiVersion: v1
kind: Secret
metadata:
  name: clif-credentials
  namespace: clif
  labels:
    app.kubernetes.io/part-of: clif-siem
type: Opaque
stringData:
  # ── ClickHouse ──
  CLICKHOUSE_USER: clif_admin
  CLICKHOUSE_PASSWORD: Cl1f_Ch@ngeM3_2026!
  CLICKHOUSE_DB: clif_logs
  # ── MinIO ──
  MINIO_ROOT_USER: clif_minio_admin
  MINIO_ROOT_PASSWORD: Cl1f_M1n10_2026!
  # ── Grafana ──
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: Cl1f_Gr@f_2026!
